<?php // @codingStandardsIgnoreFile ?>
<div class="view-detail">
    <div class="fieldset">
        <div class="actions">
            <a target="_parent" href="<?php /* @escapeNotVerified */ echo $block->getProduct()->getProductUrl() ?>"
               title="<?php /* @escapeNotVerified */ echo __('View Detail') ?>"
               class="action primary">
                <span>
                    <?php /* @escapeNotVerified */ echo __('View Detail') ?>
                </span>
            </a>
        </div>
    </div>
</div>
